---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(corrplot) # for correlation matix
library(stargazer) # visualize model fit
library(skimr) # generate summary statistics
library(car) # statistics 
library(lmtest) # linear modeling
library(sandwich)
library(tidyverse) # for data import, manipulation, viz
filter <- dplyr::filter
```

```{r}
data2$acj = data2$prbarr * data2$prbconv * data2$prbpris
data2$west_proper = ifelse(data2$west == 1 & data2$central != 1, 1, 0) 
```


```{r}
df = data2 %>% 
  mutate(
    acj = prbarr * prbconv * prbpris
    , west_proper = ifelse(west == 1 & central != 1, 1, 0)
    , central_proper = ifelse(west != 1 & central == 1, 1, 0)
    , num_minorities = density * pctmin80
    , num_ymales = density * pctymle
  ) %>% 
  mutate(
    ln_crmrte = log(crmrte)
    , ln_acj = log(prbarr * prbconv * polpc)
    , ln_wloc = log(wloc)
    , ln_wtrd = log(wtrd)
    , ln_density = log(density)
    , ln_taxpc = log(taxpc)
    , ln_pctymle = log(pctymle)
    ) %>% 
  mutate(
    acj = prbarr * prbconv * polpc
    , west_proper = ifelse(west == 1 & central != 1, 1, 0)
    , central_proper = ifelse(west != 1 & central == 1, 1, 0)
  ) %>% 
  select(
    ln_crmrte
    , ln_acj
    , ln_wloc
    , ln_wtrd
    , ln_taxpc
    , ln_density
    , pctmin80
    , ln_pctymle
    , num_minorities
    , num_ymales
    , urban
    , west_proper
  )
cor(df)
```

Base model
```{r}
base_md = lm(log(crmrte) ~ log(acj), data = data2)
plot(base_md)
```

H0: demographic factors do not have an impact on the model fit
```{r}
md1 = lm(log(crmrte) ~ log(acj) + log(density) + log(pctymle) + pctmin80, data = data2)
plot(md1)
```

```{r}
coeftest(md1)
```

```{r}
coeftest(md1, vcov = vcovHC)
```

Density and minority percetange are significant on explaing the variation on crime rate. Bot variables have a positive relationship with crime rate. % of young males does not explain the variation of crime rate.

```{r}
ggplot(data2, aes(x= pctymle*density , y=log(crmrte + 1))) + 
  geom_point()+
  geom_smooth(method=lm, se=FALSE)
```

```{r}
interac_md2 = lm(log(crmrte) ~ log(acj) + log(pctymle)*log(density) + pctmin80, data = data2)
plot(interac_md2)
```

```{r}
coeftest(interac_md2, vcov= vcovHC)
```

```{r}
md3 = lm(log(crmrte) ~ log(acj) +  log(density*pctmin80) + log(pctymle), data = data2)
plot(md3)
```
```{r}
coeftest(md3, vcov.= vcovHC)
```

```{r}
interact_md4 =  lm(log(crmrte) ~ log(acj) +  density*pctmin80 + log(pctymle), data = data2)
plot(interact_md4)
```

```{r}
interac_md5 = lm(log(crmrte) ~ log(acj) + pctymle*density + pctmin80, data = data2)
plot(interac_md5)
```


```{r}
se = sqrt(diag(vcovHC(base_md)))
se1 = sqrt(diag(vcovHC(md1)))
se2 = sqrt(diag(vcovHC(interac_md2)))
se3 = sqrt(diag(vcovHC(md3)))
se4 = sqrt(diag(vcovHC(interact_md4)))
se5 = sqrt(diag(vcovHC(interac_md5)))
```

```{r}
stargazer(
  base_md
  , md1
  , interac_md2
  , md3
  , interact_md4
  , interac_md5
  , type = "text"
  , se = list(se, se1, se2, se3, se4, se5)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```

```{r}
demo_md1 = lm(log(crmrte) ~ log(acj) + pctmin80, data = data2)
plot(demo_md1)
```

```{r}
demo_md2 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80), data = data2)
plot(demo_md2)
```

```{r}
s2_demo1 = sqrt(diag(vcovHC(demo_md1)))
s2_demo2 = sqrt(diag(vcovHC(demo_md2)))
```

```{r}
stargazer(
  base_md
  , demo_md1
  , demo_md2
  , type = "text"
  , se = list(se, s2_demo1, s2_demo2)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```

```{r}
geo_md1 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + west_proper, data = data2)
plot(geo_md1)
```

```{r}
geo_md2 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + west_proper + urban, data = data2)
plot(geo_md2)
```

```{r}
geo_md3 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + urban, data = data2)
plot(geo_md3)
```

```{r}
se_geo1 = sqrt(diag(vcovHC(geo_md1)))
se_geo2 = sqrt(diag(vcovHC(geo_md2)))
se_geo3 = sqrt(diag(vcovHC(geo_md3)))
```

```{r}
stargazer(
  demo_md2
  , geo_md1
  , geo_md2
  , geo_md3
  , type = "text"
  , se = list(s2_demo2, se_geo1, se_geo2)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```

```{r}
mix_md1 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(mix), data = data2)
plot(mix_md1)
```

```{r}
se_mix1 = sqrt(diag(vcovHC(mix_md1)))
```


```{r}
stargazer(
  demo_md2
  , mix_md1
  , type = "text"
  , se = list(s2_demo2, se_mix1)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```

```{r}
eco_md1 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(taxpc), data = data2)
plot(eco_md1)
```

```{r}
eco_md2 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(wloc), data = data2)
plot(eco_md2 )
```

```{r}
eco_md3 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(wloc) + log(taxpc), data = data2)
plot(eco_md3)
```

```{r}
eco_md4 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(wloc)*log(taxpc), data = data2)
plot(eco_md4)
```

```{r}
eco_md5 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + taxpc + taxpc^2, data = data2)
plot(eco_md5)
```

```{r}
eco_md6 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + wloc + wloc^2, data = data2)
plot(eco_md6)
```

```{r}
eco_md7 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(wloc)*log(wloc), data = data2)
plot(eco_md7)
```


```{r}
se_eco1 = sqrt(diag(vcovHC(eco_md1)))
se_eco2 = sqrt(diag(vcovHC(eco_md2)))
se_eco3 = sqrt(diag(vcovHC(eco_md3)))
se_eco4 = sqrt(diag(vcovHC(eco_md4)))
se_eco5 = sqrt(diag(vcovHC(eco_md5)))
se_eco6 = sqrt(diag(vcovHC(eco_md6)))
se_eco7 = sqrt(diag(vcovHC(eco_md7)))
```

```{r}
stargazer(
   eco_md1
  , eco_md2
  , eco_md3
  , eco_md4
  , eco_md5
  , type = "text"
  , se = list(s2_demo2, se_eco1, se_eco2, se_eco3, se_eco4, se_eco5)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```


```{r}
stargazer(
  eco_md6
  , eco_md7
  , type = "text"
  , se = list(s2_demo2, se_eco5, se_eco6)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```


```{r}
m4 <- lm(log(crmrte) ~ log(acj) + log(avgsen) + log(density) + mix  + pctymle + pctmin80 + west + central + urban  + log(taxpc) , data = data2) 
```

```{r}
combined_md1 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(taxpc) + urban, data = data2)
plot(combined_md1)
```

```{r}
combined_md1 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + log(taxpc) + urban, data = data2)
plot(combined_md1)
```

```{r}
combined_md2 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + taxpc*taxpc + urban, data = data2)
plot(combined_md2)
```

```{r}
combined_md3 = lm(log(crmrte) ~ log(acj) + log(density * pctmin80) + taxpc*taxpc + wloc*wloc + urban, data = data2)
plot(combined_md3)
```

```{r}
se_m4 = sqrt(diag(vcovHC(m4)))
se_combined_md1 = sqrt(diag(vcovHC(combined_md1)))
se_combined_md2 = sqrt(diag(vcovHC(combined_md2)))
se_combined_md3 = sqrt(diag(vcovHC(combined_md3)))
```

```{r}
stargazer(
  demo_md2
  , m4
  , combined_md1
  , combined_md2
  , combined_md3
  , type = "text"
  , se = list(s2_demo2, se_m4, se_combined_md1)
  , star.cutoffs = c(0.05, 0.01, 0.001)
)
```

```{r}
plot(log(data2$crmrte), combined_md1$fitted.values, main = "Crime Rate - Actual vs Predicted")
abline(a=0,b=1)
```

